### ISSUE TITLE
[IE11]  'wrap-reverse' renders without implicit 'align-items:flex-end'

### ISSUE THREAD

**Issue by felics** [felics/hagrid#13]
All tested browsers render `wrap-reverse` with implicit `align-items: flex-end`. IE 10/11 renders `wrap-reverse`with an implicit `align-items: flex-start`

[Testcase](http://codepen.io/anon/pen/PwXbbR)

[Workaround](http://codepen.io/anon/pen/LEMyVN)

```scss
  @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) { 
    align-items: flex-end;
}

```

[Bug Report](https://connect.microsoft.com/IE/feedback/details/1191235/ie11-flexbox-flex-wrap-wrap-reverse-standard-item-aligning-inconsistent-with-other-browser-engines) | [Flexbugs](https://github.com/philipwalton/flexbugs/issues/27)
