### ISSUE TITLE
Margin/Modifier-Selector Variable

### ISSUE THREAD

**Issue by felics** [felics/hagrid#22]
Right now, the output code looks like this:
```css
.grid > * {
    padding-left: 0.75rem;
    padding-right: 0.75rem;
}
```
It would be nice to be able to manipulate `> *` via a variable to use a selector that is not as costly, e.g. .list-item or smth if wanted.
