### ISSUE TITLE
What happened with the `auto`modifier?

### ISSUE THREAD

**Issue by renatocarvalho** [felics/hagrid#30]
Hey @felics, I was wondering why you removed the `auto` modifier. Is there a way to accomplish the same behavior without that?

**Comment by felics** [comment]
@renatocarvalho `auto` was removed because it's the only modifier that doesn't degrade gracefully on the fallback and works inconsistently with the rest of the grid's modifiers. On top, it's super easy to do with vanilla flexbox, it's basically only setting: 

```scss
.grid {
    display: flex;
    flex: 1 1 auto;
}

.grid-item {
     flex: 1 1 0%;
}

.grid-item.example {
    flex: 0 0 auto;
    width: 50%;
}
```

This will be readded once the need for a fallback is gone.
